### ISSUE TITLE
update kernel4.19 and updategrub error

### ISSUE THREAD

**Issue by lxd5866** [cloudnativer/kube-install#20]
update kernel4.19 and updategrub is a dangerous operation， can we add a confirmation  option  to this step。I've had two boot failures because of this，and I prefer to do this manually

**Comment by lxd5866** [comment]
I've had two boot failures because of this

**Comment by houseonline** [comment]
Thank you for your feedback!

The default kernel of CentOS 7 lacks modules such as br_netfilter required by the kubernetes network, and the kernel needs to be optimized. Therefore, `kube-install` will upgrade and optimize the kernel of the centos7 operating system by default. At some point, you may encounter the problem that the host cannot start.
We will add the `--skipupgradekernel` function in v0.7.3 and above. You can choose whether to skip the operating system kernel upgrade, and then you can optimize the centos7 kernel problem yourself.

In addition, the default kernel of CentOS 8, RHEL 8, SUSE Linux 15, Ubuntu 20, etc. does not have this problem, so the kernel will not be automatically upgraded, and it can be successfully installed and used!

**Comment by cloudnativer** [comment]
Thank you for your feedback!

We will add the --skipupgradekernel function in v0.7.3 and above. You can choose whether to skip the operating system kernel upgrade, and then you can optimize the centos7 kernel problem yourself.

**Comment by cloudnativer** [comment]
Screenshot of function preview of new version:

![kube-install-auosk001](https://user-images.githubusercontent.com/62274882/142643640-68ea7f0b-72b0-4644-b212-257a65891c04.png)

**Comment by lxd5866** [comment]
thanks
