### ISSUE TITLE
do we have plan to support calico?

### ISSUE THREAD

**Issue by huangxuelun** [cloudnativer/kube-install#21]
do we have plan to support calico?

**Comment by cloudnativer** [comment]
Thank you for your feedback!

We will add the --skipupgradekernel function in v0.7.3 and above. In the new version, you can choose to install CNI plug-ins such as flannel or calico.

**Comment by cloudnativer** [comment]
Screenshot of function preview of new version:

![kube-install-cnip](https://user-images.githubusercontent.com/62274882/142643717-1c32441b-2afd-47cc-8944-2fc64470c273.png)

**Comment by huangxuelun** [comment]
great job. thanks.
