### ISSUE TITLE
集群安装成功后，在master节点上执行kubectl get nodes -A命令时只能看到两个工作节点，看不到master节点

### ISSUE THREAD

**Issue by haolipeng** [cloudnativer/kube-install#24]
![image](https://user-images.githubusercontent.com/6583143/145365031-902922d5-af27-43f6-ab10-94807d79a396.png)

**Comment by haolipeng** [comment]
搭建环境
master ：192.168.29.141
node1 ：192.168.29.142
node2：192.168.29.143
采用普通方式搭建的集群，执行kubectl get nodes -A 时，是能看到既有master节点，也有node节点的

**Comment by houseonline** [comment]
如果你使用kubeadm的安裝方式，是使用容器來部署k8s，所以你會看見master和node都在容器裡面。然後get出來，發現master、node都在node列表中。

kube-install是純二進制的安裝，與kubeadm有著本質區別，node列表中只有node。 kube-install是希望返璞歸真，讓node是node，master是master。
master只是一個管控程序，不運行業務容器的。只有node才是真正運行容器的計算主機。

你可以用kubectl get cs查看master和etcd狀態。你可以用kubectl get node查看node狀態。

**Comment by haolipeng** [comment]
非常感谢，明白了

**Comment by haolipeng** [comment]
问题已经得到解决
