### ISSUE TITLE
dashboard blank page

### ISSUE THREAD

**Issue by 176883745** [cloudnativer/kube-install#43]
I get a blank white k8s dashboard after installation:
![image](https://user-images.githubusercontent.com/120629608/217762132-d8dce075-b554-49f7-b98d-d2f969fcfffd.png)
any idea?

**Comment by houseonline** [comment]
It may be related to your browser settings or compatibility. 

- Skip security restrictions? 
- Try changing your browser?


By the way, you can run `kubectl get pod - n kube-system | grep dashboard` to see if the dashboard container is running.

**Comment by 176883745** [comment]
> It may be related to your browser settings or compatibility.
> 
> * Skip security restrictions?
> * Try changing your browser?
> 
> By the way, you can run `kubectl get pod - n kube-system | grep dashboard` to see if the dashboard container is running?

Yes, you're right, it works on Chrome, thank you : )
